name: Git Pre-Release

on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+-pre**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Moving build to dist-directory
        run: ./copyFilesToDist.sh
        shell: bash
        env:
          GITHUB_REF_VARIABLE: ${{ steps.vars.outputs.tag }}
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME_PREFIX: "Pre-Release "
          PRE_RELEASE: true
        with:
          args: |
            dist/wahooMapsCreator-*.zip
            darwin-amd64.zip
            linux-amd64.zip
            windows-amd64.zip
