name: Create pre-release with .zip files

on:
  push:
    branches:
      - "release-*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UNRELEASED: "update"
          ALLOW_EMPTY_CHANGELOG: true
        with:
          args: |
            dist/*.zip
            darwin-amd64.zip
            linux-amd64.zip
            windows-amd64.zip
