name: Create release with .zip files on new tag

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME_PREFIX: "Release "
        with:
          args: |
            dist/*.zip
            darwin-amd64.zip
            linux-amd64.zip
            windows-amd64.zip
